SELECT YEAR
     , MONTH
     , GENDER
     , COUNT(DISTINCT(USER_ID)) AS USERS
FROM 
    (
        SELECT EXTRACT(YEAR FROM T1.SALES_DATE) AS YEAR
             , EXTRACT(MONTH FROM T1.SALES_DATE) AS MONTH
             , T2.GENDER AS GENDER
        	 , T1.USER_ID
          FROM ONLINE_SALE T1
          INNER JOIN USER_INFO T2
                 ON T1.USER_ID = T2.USER_ID
                 AND T2.GENDER IS NOT NULL
    )
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER
