SELECT T1.YEAR
     , T1.MONTH
     , T1.GENDER
     , COUNT(DISTINCT(T1.USER_ID)) AS USERS
FROM 
    (
        SELECT YEAR(T1.SALES_DATE) AS YEAR
             , MONTH(T1.SALES_DATE) AS MONTH
             , T2.GENDER AS GENDER
        	 , T1.USER_ID
          FROM ONLINE_SALE T1
          INNER JOIN USER_INFO T2
                 ON T1.USER_ID = T2.USER_ID
                 AND T2.GENDER IS NOT NULL
    ) T1
GROUP BY T1.YEAR, T1.MONTH, T1.GENDER
ORDER BY T1.YEAR, T1.MONTH, T1.GENDER