SELECT CAR_ID
	 , CAR_TYPE
	 , FEE
FROM
(
	SELECT T1.CAR_ID AS CAR_ID
		 , T1.CAR_TYPE AS CAR_TYPE
		 , ROUND(((T1.DAILY_FEE * 30)* (100 - T3.DISCOUNT_RATE)/100),0) AS FEE
	 FROM CAR_RENTAL_COMPANY_CAR T1
	INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
			ON T1.CAR_ID = T2.CAR_ID
	INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
			ON T1.CAR_TYPE = T3.CAR_TYPE
	WHERE T1.CAR_TYPE IN ('세단','SUV')		
	  AND T1.CAR_ID NOT IN
		 (
			SELECT A1.CAR_ID
			  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A1
			 WHERE A1.START_DATE <= '2022-11-30' 
			   AND A1.END_DATE >= '2022-11-01'
		  )
	  AND T3.DURATION_TYPE = '30일 이상'
    GROUP BY 1, 2, 3
) F1    
GROUP BY 1, 2, 3
HAVING FEE >=500000 AND FEE <2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID