SELECT T1.MONTH
     , T1.CAR_ID
     , COUNT(HISTORY_ID)AS RECORDS
FROM
(
SELECT CAR_ID AS CAR_ID
     , EXTRACT(MONTH FROM START_DATE) AS MONTH
     , COUNT(HISTORY_ID) OVER (PARTITION BY CAR_ID) AS CNT
	 , HISTORY_ID AS HISTORY_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
) T1
WHERE T1.CNT >= 5
GROUP BY T1.MONTH, T1.CAR_ID
ORDER BY T1.MONTH, T1.CAR_ID DESC