SELECT T1.HOUR
	 , COUNT(T2.TIME) AS COUNT
FROM (SELECT LEVEL-1 AS HOUR 
	    FROM DUAL 
	  CONNECT BY level <25) T1
LEFT OUTER JOIN (SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))AS TIME 
				   FROM ANIMAL_OUTS) T2 
			ON T1.HOUR = T2.TIME
GROUP BY T1.HOUR
ORDER BY T1.HOUR;