-- WITH RECURSIVE 구문은 가상 테이블을 생성하면서 가상 테이블 자신의 값을 참조하여 값을 결정할 때 사용된다. 
WITH RECURSIVE CTE AS(
	SELECT 0 AS NUM
	UNION ALL
	SELECT NUM+1
	FROM CTE
	WHERE NUM < 23 
)
SELECT T1.NUM
	, COUNT(HOUR) AS COUNT 
FROM CTE T1
LEFT OUTER JOIN (SELECT HOUR(DATETIME) AS HOUR 
				   FROM ANIMAL_OUTS) T2
			 ON T1.NUM = T2.HOUR
GROUP BY T1.NUM
ORDER BY T1.NUM