SELECT T1.MEMBER_NAME AS MEMBER_NAME
     , T2.REVIEW_TEXT AS REVIEW_TEXT
     , TO_CHAR(T2.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE T1
INNER JOIN REST_REVIEW T2
        ON T1.MEMBER_ID = T2.MEMBER_ID
WHERE T2.MEMBER_ID IN (
						SELECT MEMBER_ID
						  FROM REST_REVIEW
						  GROUP BY MEMBER_ID
							HAVING COUNT(MEMBER_ID) = (SELECT MAX(COUNT(MEMBER_ID))
												FROM REST_REVIEW
											GROUP BY MEMBER_ID )
						   
					  )
ORDER BY T2.REVIEW_DATE, T2.REVIEW_TEXT;