SELECT T1.AUTHOR_ID
	 , T2.AUTHOR_NAME
	 , T1.CATEGORY
	 , SUM(T3.SALES * T1.PRICE) AS TOTAL_SALES
FROM BOOK T1
INNER JOIN AUTHOR T2
		ON T1.AUTHOR_ID = T2.AUTHOR_ID
INNER JOIN BOOK_SALES T3
		ON T1.BOOK_ID = T3.BOOK_ID
WHERE T3.SALES_DATE LIKE "2022-01-%"
GROUP BY T2.AUTHOR_NAME, T1.CATEGORY
ORDER BY T1.AUTHOR_ID, T1.CATEGORY DESC 