SELECT HOUR
	 , COUNT
FROM ( 
		SELECT EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))AS HOUR
			 , COUNT(ANIMAL_ID) AS COUNT 
		FROM ANIMAL_OUTS
		GROUP BY EXTRACT(HOUR FROM CAST(DATETIME AS TIMESTAMP))
	 )
WHERE HOUR BETWEEN 9 AND 19
ORDER BY HOUR
